### PR TITLE
Wasm support

### PR DESCRIPTION
**Pull request by gorazdko**
## Abstract

This PR implements wasm support based on #6 by @AndreasGassmann

Needs https://github.com/BlockchainCommons/bc-shamir/pull/33

Close #6, #3

## Note for reviewers

I changed the type of `threshold` and `count` in sskr_group_descriptor_struct from `size_t` to `uint8_t` which should be enough imo. If it's not we can change it to some other standard, platform independent type. See the reason d8e5af9f48298db9342bd6607892f6671f016e18 why

```c
typedef struct sskr_group_descriptor_struct {
    uint8_t threshold;
    uint8_t count;
} sskr_group_descriptor;
```

### CODE REVIEW

**Comment by gorazdko** [comment]
@AndreasGassmann I've added your attribution here 81691de
Let me know how you would like to have the wording.

**Comment by AndreasGassmann** [comment]
Thanks for the PR and the mention. I'll test this as soon as possible.

Have you looked into compiling the code without using Emscripten? The 100+ kb of "glue code" seem a bit much and it might be possible to reduce or get rid of it.

**Comment by AndreasGassmann** [comment]
@gorazdko Did the shares that are generated work for you? I got the following shares:

```
0: "12f311010040eacbfac49091aaf01ce96b181308b0"
1: "12f3110101fb3455eacbf8f4324ec8e1687e0a0cc9"
2: "12f31101022d4decdada405b8197aff96dd4210042"
3: "12f3111200dc6c8cb2a838781c53df059c651748ec"
4: "12f31112014a68772cb9248c54279426ae5d6fa3e7"
5: "12f31112025fdeceb5985a5d371e63ae93c572059f"
6: "12f3111203c9da352b8946a97f6a288da1fd0aee94"
7: "12f311120427cd823c808f47906b14d13553bfe485"
```

I then used the `seedtool` to convert some of them to bytewords

```
vscode ➜ /workspaces/bc-seedtool-cli (master ✗) $ seedtool --in hex --out btw 12f311010040eacbfac49091aaf01ce96b181308b0
brag wolf body acid able fizz wand stub zaps sets math maze peck what code wall jade cats brew away puff zero dice vial drop
vscode ➜ /workspaces/bc-seedtool-cli (master ✗) $ seedtool --in hex --out btw 12f3110101fb3455eacbf8f4324ec8e1687e0a0cc9
brag wolf body acid acid zero edge gyro wand stub yoga work easy girl soap very iris knob back barn solo mild luck into duty
vscode ➜ /workspaces/bc-seedtool-cli (master ✗) $ seedtool --in hex --out btw 12f3111200dc6c8cb2a838781c53df059c651748ec
brag wolf body brag able undo jazz luck purr paid exit keys code guru user arch news inch cash fund wasp gyro fizz barn wall
vscode ➜ /workspaces/bc-seedtool-cli (master ✗) $ seedtool --in hex --out btw 12f31112014a68772cb9248c54279426ae5d6fa3e7
brag wolf body brag acid game iris kept draw rich dark luck gush deli meow days pool hill jowl omit void fuel dice purr lung
vscode ➜ /workspaces/bc-seedtool-cli (master ✗) $ seedtool --in hex --out btw 12f31112025fdeceb5985a5d371e63ae93c572059f
brag wolf body brag also hope urge taco race monk heat hill exam cook idea pool menu silk jump arch note next horn hard tiny
```

Then I try to combine them:

```
vscode ➜ /workspaces/bc-seedtool-cli (master ✗) $ seedtool --in sskr
brag wolf body acid able fizz wand stub zaps sets math maze peck what code wall jade cats brew away puff zero dice vial drop
brag wolf body acid acid zero edge gyro wand stub yoga work easy girl soap very iris knob back barn solo mild luck into duty
brag wolf body brag able undo jazz luck purr paid exit keys code guru user arch news inch cash fund wasp gyro fizz barn wall
brag wolf body brag acid game iris kept draw rich dark luck gush deli meow days pool hill jowl omit void fuel dice purr lung
brag wolf body brag also hope urge taco race monk heat hill exam cook idea pool menu silk jump arch note next horn hard tiny
seedtool: Not a valid SSKR share.
```

Am I doing something wrong?

**Comment by gorazdko** [comment]
Yes, you're missing cbor.

So the first share should be d901355512f311010040eacbfac49091aaf01ce96b181308b0

then you encode it into bytewords

source: https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md

**Comment by gorazdko** [comment]
@AndreasGassmann note that building with `emcc -Os` optimizes for code size:

`sskr.js` drops from 120KB to 15.5KB and `sskr.wasm` drops from 42KB to 14.3KB

We can put that as default.

**Review by wolfmcnally — APPROVED** [review]
Didn't test actual WASM, but LGTM.

**Pull request merged**
